# 6.5.2 Create Heatmaps for Weather Parameters

In [1]:
# Import dependencies
import os
import pandas as pd
import requests
import gmaps

# Import the API key.
from config import g_key

In [2]:
# Store the CSV created in part one into a DataFrame
df_city_data = pd.read_csv(os.path.join('./weather_data/cities.csv'))

df_city_data.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Beroroha,MG,2022-05-08 22:00:47,-21.6667,45.1667,68.68,79,0,1.86
1,1,Rikitea,PF,2022-05-08 22:00:47,-23.1203,-134.9692,76.37,77,78,19.69
2,2,Albany,US,2022-05-08 22:00:11,42.6001,-73.9662,63.88,29,100,1.01
3,3,Saint George,US,2022-05-08 21:57:19,37.1041,-113.5841,84.63,10,0,36.82
4,4,Atikokan,CA,2022-05-08 22:00:49,48.7555,-91.6216,48.70,93,100,13.33

In [3]:
# Get city_data data types
df_city_data.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

## Create a Maximum Temperature Heatmap

# Heatmap of temperature
# Get the latitude and longitude
locations = df_city_data[['Lat','Lng']]

# Get the maximum temperature
## temp_max = df_city_data['Max Temp']
## temp_max_min = min(temp_max)
temp_max = [max(temp,0) for temp in df_city_data['Max Temp']]

# Assign the figure variable
fig = gmaps.figure()

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(locations, temp_max)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

## Adjust Heatmap Zoom, Intensity, and Point Radius

# Heatmap of temperature
# Get the latitude and longitude
locations = df_city_data[['Lat','Lng']]

# Get the maximum temperature
## temp_max = df_city_data['Max Temp']
## temp_max_min = min(temp_max)
temp_max = [max(temp,0) for temp in df_city_data['Max Temp']]

# Assign the figure variable
fig = gmaps.figure(center=(30.0,31.0), zoom_level=1.5)

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(locations, temp_max)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

In [4]:
# Heatmap of temperature
# Get the latitude and longitude
locations = df_city_data[['Lat','Lng']]

# Get the maximum temperature
## temp_max = df_city_data['Max Temp']
## temp_max_min = min(temp_max)
temps_max = [max(temp,0) for temp in df_city_data['Max Temp']]

# Assign the figure variable
fig = gmaps.figure(
    center=(30.0,31.0),
    zoom_level=1.5
)

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(
    locations,
    temps_max,
    dissipating=False,
    max_intensity=300,
    point_radius=4
)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

## Create a Percent Humidity Heatmap

In [5]:
# Heatmap of humidity
# Get the latitude and longitude
locations = df_city_data[['Lat','Lng']]

# Get the humidity
humidity = df_city_data['Humidity']

# Assign the figure variable
fig = gmaps.figure(
    center=(30.0,31.0),
    zoom_level=1.5
)

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(
    locations,
    humidity,
    dissipating=False,
    max_intensity=300,
    point_radius=4
)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

## Create a Percent Cloudiness Heatmap

In [6]:
# Heatmap of cloudiness
# Get the latitude and longitude
locations = df_city_data[['Lat','Lng']]

# Get the cloudiness
clouds = df_city_data['Cloudiness']

# Assign the figure variable
fig = gmaps.figure(
    center=(30.0,31.0),
    zoom_level=1.5
)

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(
    locations,
    weights=clouds,
    dissipating=False,
    max_intensity=300,
    point_radius=4
)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

## Create a Wind Speed Heatmap

In [7]:
# Heatmap of windspeed
# Get the latitude and longitude
locations = df_city_data[['Lat','Lng']]

# Get the cloudiness
wind = df_city_data['Wind Speed']

# Assign the figure variable
fig = gmaps.figure(
    center=(30.0,31.0),
    zoom_level=1.5
)

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(
    locations,
    weights=wind,
    dissipating=False,
    max_intensity=300,
    point_radius=4
)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

# 6.5.3 Get Vacation Criteria

In [8]:
# Ask the customer to add a minimum and maximum temperature value
temp_min = float(input("What is the lowest maximum temperature you would like for your trip? "))
temp_max = float(input("What is the highest maximum temperature you would like for your trip? "))

What is the lowest maximum temperature you would like for your trip? 75
What is the highest maximum temperature you would like for your trip? 95

In [9]:
df_preferred_cities = df_city_data.loc[(temp_min <= df_city_data['Max Temp']) & (df_city_data['Max Temp'] <= temp_max)]

df_preferred_cities.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Rikitea,PF,2022-05-08 22:00:47,-23.1203,-134.9692,76.37,77,78,19.69
3,3,Saint George,US,2022-05-08 21:57:19,37.1041,-113.5841,84.63,10,0,36.82
6,6,Hilo,US,2022-05-08 21:59:03,19.7297,-155.0900,92.28,92,52,5.01
8,8,Puerto Ayora,EC,2022-05-08 22:00:52,-0.7393,-90.3518,75.04,79,51,9.44
11,11,Bengkulu,ID,2022-05-08 22:00:54,-3.8004,102.2655,77.00,82,90,3.74
14,14,Harper,LR,2022-05-08 22:00:56,4.3750,-7.7169,79.18,86,100,5.66
28,28,Atuona,PF,2022-05-08 22:01:05,-9.8000,-139.0333,78.60,75,1,15.14
30,30,Alofi,NU,2022-05-08 22:01:06,-19.0595,-169.9187,80.22,78,89,17.20
31,31,Dera Bugti,PK,2022-05-08 22:01:07,29.0307,69.1510,85.50,26,0,3.49
39,39,Dawei,MM,2022-05-08 22:01:14,14.0833,98.2000,77.63,88,100,2.53

In [10]:
df_preferred_cities.count()

City_ID       169
City          169
Country       169
Date          169
Lat           169
Lng           169
Max Temp      169
Humidity      169
Cloudiness    169
Wind Speed    169
dtype: int64

# 6.5.4 Map Vacation Criteria

## Get Travel Destinations

In [11]:
# Create df_hotels DataFrame to store hotel names, city, country, max temp, and coordinates
# hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
# hotel_df["Hotel Name"] = ""
df_hotels = df_preferred_cities[['City','Country','Max Temp','Lat','Lng']].copy()
df_hotels['Hotel Name'] = ''

df_hotels.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
1        Rikitea      PF     76.37 -23.1203 -134.9692
3   Saint George      US     84.63  37.1041 -113.5841
6           Hilo      US     92.28  19.7297 -155.0900
8   Puerto Ayora      EC     75.04  -0.7393  -90.3518
11      Bengkulu      ID     77.00  -3.8004  102.2655
14        Harper      LR     79.18   4.3750   -7.7169
28        Atuona      PF     78.60  -9.8000 -139.0333
30         Alofi      NU     80.22 -19.0595 -169.9187
31    Dera Bugti      PK     85.50  29.0307   69.1510
39         Dawei      MM     77.63  14.0833   98.2000

## Retrieve Hotels from a Nearby Search

### Set the Parameters for a Nearby Search

In [12]:
# Set hotel search parameters
input_parameters = {
    'radius': 5000,  # meters
    'type': 'lodging',  # See https://developers.google.com/maps/documentation/places/web-service/supported_types
    'key': g_key
}

## Iterate Through hotel_df DataFrame

# Iterate through the DataFrame
for index, row in df_hotels.iterrows():

    # Get the latitude and longitude.
    lat = row['Lat']
    lng = row['Lng']

    # Add the latitude and longitude to location key for the params dictionary.
    input_parameters['location'] = f'{lat},{lng}'

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    
    # Make request and get JSON data from search
    hotels = requests.get(base_url,params=input_parameters).json()
    
    # Get first hotel from results and store the name
    df_hotels.loc[index,'Hotel Name'] = hotels['results'][0]['name']

In [13]:
# Iterate through the DataFrame
for index, row in df_hotels.iterrows():

    # Get the latitude and longitude.
    lat = row['Lat']
    lng = row['Lng']

    # Add the latitude and longitude to location key for the params dictionary.
    input_parameters['location'] = f'{lat},{lng}'

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    
    # Make request and get JSON data from search
    hotels = requests.get(base_url,params=input_parameters).json()
    
    # Get first hotel from results and store the name
    try:
        df_hotels.loc[index,'Hotel Name'] = hotels['results'][0]['name']
    except IndexError:
        # With no API key, they'll all be errors
#         if index == 1:
#             df_hotels.loc[index,'Hotel Name'] = 'Skipped'  # For error checking
        print(f"Hotel near {df_hotels.loc[index,'City']}, {df_hotels.loc[index,'Country']} not found… skipping.")

Hotel near Rikitea, PF not found… skipping.
Hotel near Saint George, US not found… skipping.
Hotel near Hilo, US not found… skipping.
Hotel near Puerto Ayora, EC not found… skipping.
Hotel near Bengkulu, ID not found… skipping.
Hotel near Harper, LR not found… skipping.
Hotel near Atuona, PF not found… skipping.
Hotel near Alofi, NU not found… skipping.
Hotel near Dera Bugti, PK not found… skipping.
Hotel near Dawei, MM not found… skipping.
Hotel near Kapaa, US not found… skipping.
Hotel near Hirara, JP not found… skipping.
Hotel near Hithadhoo, MV not found… skipping.
Hotel near Carolina, PR not found… skipping.
Hotel near Vanimo, PG not found… skipping.
Hotel near Belmonte, BR not found… skipping.
Hotel near Itapirapua, BR not found… skipping.
Hotel near Cabedelo, BR not found… skipping.
Hotel near Ahuimanu, US not found… skipping.
Hotel near Avarua, CK not found… skipping.
Hotel near Faanui, PF not found… skipping.
Hotel near Taoudenni, ML not found… skipping.
Hotel near Enterprise, US not found… skipping.
Hotel near Ambulu, ID not found… skipping.
Hotel near Daru, PG not found… skipping.
Hotel near Vaini, TO not found… skipping.
Hotel near Vaitape, PF not found… skipping.
Hotel near Raga, SS not found… skipping.
Hotel near San Patricio, US not found… skipping.
Hotel near Tutoia, BR not found… skipping.
Hotel near Soyo, AO not found… skipping.
Hotel near Manggar, ID not found… skipping.
Hotel near Kuantan, MY not found… skipping.
Hotel near Bachaquero, VE not found… skipping.
Hotel near Tessalit, ML not found… skipping.
Hotel near Cabo San Lucas, MX not found… skipping.
Hotel near Islamkot, PK not found… skipping.
Hotel near Ewa Beach, US not found… skipping.
Hotel near Celestun, MX not found… skipping.
Hotel near San Cristobal, VE not found… skipping.
Hotel near Oranjestad, AW not found… skipping.
Hotel near San Fernando, PH not found… skipping.
Hotel near Birao, CF not found… skipping.
Hotel near Alyangula, AU not found… skipping.
Hotel near Rodrigues Alves, BR not found… skipping.
Hotel near Sao Felix Do Xingu, BR not found… skipping.
Hotel near Butaritari, KI not found… skipping.
Hotel near Poum, NC not found… skipping.
Hotel near Carauari, BR not found… skipping.
Hotel near Kavieng, PG not found… skipping.
Hotel near Georgetown, MY not found… skipping.
Hotel near Salalah, OM not found… skipping.
Hotel near Nhulunbuy, AU not found… skipping.
Hotel near Marsh Harbour, BS not found… skipping.
Hotel near Victoria, HK not found… skipping.
Hotel near Cayenne, GF not found… skipping.
Hotel near Bandarbeyla, SO not found… skipping.
Hotel near Umm Kaddadah, SD not found… skipping.
Hotel near Kousseri, CM not found… skipping.
Hotel near Neiafu, TO not found… skipping.
Hotel near Catuday, PH not found… skipping.
Hotel near Freetown, SL not found… skipping.
Hotel near Sao Gabriel Da Cachoeira, BR not found… skipping.
Hotel near Port Blair, IN not found… skipping.
Hotel near Bixby, US not found… skipping.
Hotel near Balikpapan, ID not found… skipping.
Hotel near Jamame, SO not found… skipping.
Hotel near Sohag, EG not found… skipping.
Hotel near Morant Bay, JM not found… skipping.
Hotel near Buritis, BR not found… skipping.
Hotel near Sola, VU not found… skipping.
Hotel near Maraba, BR not found… skipping.
Hotel near Kavaratti, IN not found… skipping.
Hotel near Maceio, BR not found… skipping.
Hotel near Marzuq, YE not found… skipping.
Hotel near Biak, ID not found… skipping.
Hotel near Sabang, ID not found… skipping.
Hotel near Tiarei, PF not found… skipping.
Hotel near Itarema, BR not found… skipping.
Hotel near Cape Canaveral, US not found… skipping.
Hotel near Vila Velha, BR not found… skipping.
Hotel near West Bay, KY not found… skipping.
Hotel near Nicoya, CR not found… skipping.
Hotel near Berbera, SO not found… skipping.
Hotel near Dingle, PH not found… skipping.
Hotel near Roebourne, AU not found… skipping.
Hotel near Camocim, BR not found… skipping.
Hotel near Nishihara, JP not found… skipping.
Hotel near Pochutla, MX not found… skipping.
Hotel near La Macarena, CO not found… skipping.
Hotel near Lufilufi, WS not found… skipping.
Hotel near Road Town, VG not found… skipping.
Hotel near Trairi, BR not found… skipping.
Hotel near Kokopo, PG not found… skipping.
Hotel near Dibulla, CO not found… skipping.
Hotel near Quebo, GW not found… skipping.
Hotel near Bubaque, GW not found… skipping.
Hotel near Keffi, NG not found… skipping.
Hotel near Kudahuvadhoo, MV not found… skipping.
Hotel near Meulaboh, ID not found… skipping.
Hotel near Labuhan, ID not found… skipping.
Hotel near Ambunti, PG not found… skipping.
Hotel near Padang, ID not found… skipping.
Hotel near Kiunga, PG not found… skipping.
Hotel near Axim, GH not found… skipping.
Hotel near Salinopolis, BR not found… skipping.
Hotel near Areia Branca, BR not found… skipping.
Hotel near San Policarpo, PH not found… skipping.
Hotel near Mitsamiouli, KM not found… skipping.
Hotel near Edgewater, US not found… skipping.
Hotel near Angul, IN not found… skipping.
Hotel near General Cepeda, MX not found… skipping.
Hotel near Urucara, BR not found… skipping.
Hotel near Buala, SB not found… skipping.
Hotel near Katobu, ID not found… skipping.
Hotel near Ambon, ID not found… skipping.
Hotel near Bathsheba, BB not found… skipping.
Hotel near Merauke, ID not found… skipping.
Hotel near Matehuala, MX not found… skipping.
Hotel near Sorong, ID not found… skipping.
Hotel near Santa Rosa, PH not found… skipping.
Hotel near Deoband, IN not found… skipping.
Hotel near Aswan, EG not found… skipping.
Hotel near Kloulklubed, PW not found… skipping.
Hotel near Miri, MY not found… skipping.
Hotel near Kendari, ID not found… skipping.
Hotel near Saint-Georges, GD not found… skipping.
Hotel near Bonthe, SL not found… skipping.
Hotel near Eyl, SO not found… skipping.
Hotel near Hurghada, EG not found… skipping.
Hotel near Narasannapeta, IN not found… skipping.
Hotel near Aracoiaba, BR not found… skipping.
Hotel near Coahuayana, MX not found… skipping.
Hotel near Baracoa, CU not found… skipping.
Hotel near Huicungo, PE not found… skipping.
Hotel near Isangel, VU not found… skipping.
Hotel near Siocon, PH not found… skipping.
Hotel near Madang, PG not found… skipping.
Hotel near Awallan, PH not found… skipping.
Hotel near Bintulu, MY not found… skipping.
Hotel near Whithorn, JM not found… skipping.
Hotel near Rondonopolis, BR not found… skipping.
Hotel near Ocos, GT not found… skipping.
Hotel near Rock Sound, BS not found… skipping.
Hotel near Adrar, MR not found… skipping.
Hotel near Tiznit, MA not found… skipping.
Hotel near Mabaruma, GY not found… skipping.
Hotel near Kismayo, SO not found… skipping.
Hotel near Carlyle, US not found… skipping.
Hotel near Rosario Oeste, BR not found… skipping.
Hotel near Wajir, KE not found… skipping.
Hotel near Luziania, BR not found… skipping.
Hotel near Tual, ID not found… skipping.
Hotel near Beihai, CN not found… skipping.
Hotel near Mayor Pablo Lagerenza, PY not found… skipping.
Hotel near Azare, NG not found… skipping.
Hotel near Mattru, SL not found… skipping.
Hotel near Luganville, VU not found… skipping.
Hotel near Kuching, MY not found… skipping.
Hotel near Araguaina, BR not found… skipping.
Hotel near Kihei, US not found… skipping.
Hotel near Wawa, NG not found… skipping.
Hotel near Porto Novo, BJ not found… skipping.
Hotel near San Carlos, VE not found… skipping.
Hotel near Sibolga, ID not found… skipping.
Hotel near Ciudad Bolivar, VE not found… skipping.
Hotel near Itoman, JP not found… skipping.
Hotel near Minab, IR not found… skipping.
Hotel near Soure, BR not found… skipping.

In [14]:
df_hotels

               City Country  Max Temp      Lat       Lng Hotel Name
1           Rikitea      PF     76.37 -23.1203 -134.9692
3      Saint George      US     84.63  37.1041 -113.5841
6              Hilo      US     92.28  19.7297 -155.0900
8      Puerto Ayora      EC     75.04  -0.7393  -90.3518
11         Bengkulu      ID     77.00  -3.8004  102.2655
..              ...     ...       ...      ...       ...        ...
540         Sibolga      ID     76.39   1.7427   98.7792
541  Ciudad Bolivar      VE     84.07   8.1222  -63.5497
543          Itoman      JP     77.02  26.1247  127.6694
544           Minab      IR     82.72  27.1467   57.0801
545           Soure      BR     76.32  -0.7167  -48.5233

[169 rows x 6 columns]

## Create a Maximum Temperature Heatmap from a Hotel DataFrame

In [15]:
# Temperature heatmap for preferred locations
# Get latitude and longitude
locations = df_hotels[['Lat','Lng']]

# Get the temperatures
temps = df_hotels['Max Temp']

# Assign the figure variable
fig = gmaps.figure(
    center=(30.0,31.0),
    zoom_level=1.5
)

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(
    locations,
    weights=temps,
    dissipating=False,
    max_intensity=300,
    point_radius=4
)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Temperature heatmap for preferred locations
# Get latitude and longitude
locations = df_hotels[['Lat','Lng']]

# Get the temperatures
temps = df_hotels['Max Temp']

# Assign the figure variable
fig = gmaps.figure(
    center=(30.0,31.0),
    zoom_level=1.5
)

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(
    locations,
    weights=temps,
    dissipating=False,
    max_intensity=300,
    point_radius=4
)

# Assign markers
marker_layer = gmaps.marker_layer(locations)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Add the marker layer
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
df_hotels

               City Country  Max Temp      Lat       Lng Hotel Name
1           Rikitea      PF     76.37 -23.1203 -134.9692
3      Saint George      US     84.63  37.1041 -113.5841
6              Hilo      US     92.28  19.7297 -155.0900
8      Puerto Ayora      EC     75.04  -0.7393  -90.3518
11         Bengkulu      ID     77.00  -3.8004  102.2655
..              ...     ...       ...      ...       ...        ...
540         Sibolga      ID     76.39   1.7427   98.7792
541  Ciudad Bolivar      VE     84.07   8.1222  -63.5497
543          Itoman      JP     77.02  26.1247  127.6694
544           Minab      IR     82.72  27.1467   57.0801
545           Soure      BR     76.32  -0.7167  -48.5233

[169 rows x 6 columns]

In [18]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Maximum Temperature</dt><dd>{Max Temp}</dd>
</dl>
"""

hotel_info = [info_box_template.format(**row) for index, row in df_hotels.iterrows()]

In [19]:
# Temperature heatmap for preferred locations
# Get latitude and longitude
locations = df_hotels[['Lat','Lng']]

# Get the temperatures
temps = df_hotels['Max Temp']

# Assign the figure variable
fig = gmaps.figure(
    center=(30.0,31.0),
    zoom_level=1.5
)

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(
    locations,
    weights=temps,
    dissipating=False,
    max_intensity=300,
    point_radius=4
)

# Assign markers
marker_layer = gmaps.marker_layer(
    locations,
    info_box_content=hotel_info
)

# Add the heatmap layer
fig.add_layer(heat_layer)

# Add the marker layer
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))